application: instantlyat
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /_ah/mail/.+ 
  script: handle_mail.py 
  login: admin
  
- url: .*
  script: main.py

